import { IAppointment } from './IAppointment';
import { IPage } from './IPage';

export interface IAppointmentPage { // paging resource generated by Spring
    _embedded: {appointmentEntities: IAppointment[]};
    _links: {};
    page: IPage;
}