
/*
These interfaces will need to change when the Appointment or AppointmentTag
classes change in the Java project.
*/
interface AppointmentTag {
    name: string;
    value: string;
}

interface Appointment {
    startTime: string;
    endTime: string;
    title: string;
    location: string;
    description: string;
    restrictions: string;
    totalSlots: number;
    tags: AppointmentTag[];
    registeredUsers: string[];
    canceled: boolean;
}

interface Page { // generated by Spring
    size: number;
    totalElements: number;
    totalPages: number;
    number: number;
}

interface AppointmentPage { // paging resource generated by Spring
    _embedded: {appointmentEntities: Appointment[]};
    _links: {};
    page: Page;
}

export {
    AppointmentTag,
    Appointment,
    Page,
    AppointmentPage
};