# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install Angular app dependencies
        run: |
          cd ./angular-app
          npm install -g @angular/cli
          npm install                 # installs non-global dependencies
          cd ..
      
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      - name: Allow pipeline to execute wrapper # https://stackoverflow.com/a/58612930
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'
          if-no-files-found: error
  
  # GitHub requires convoluted ways of checking if an environment variable is set
  # https://github.com/actions/runner/issues/1189
  # https://stackoverflow.com/a/70249520
  should-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    outputs:
      foo: ${{ steps.foo.outputs.is-defined}}
    steps:
      - id: foo
        env:
          publishProfile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          appName: ${{ secrets.AZUREAPPSERVICE_APPNAME }}
        if: "${{ env.publishProfile != '' && env.appName != '' }}"
        run: echo "::set-output name=is-defined::true"
  
  do-not-deploy:
    # only runs if publish profile or app name are not set in GitHub
    if: ${{ needs.should-deploy.outputs.foo != 'true' }}
    runs-on: ubuntu-latest
    needs: [should-deploy]
    steps:
      - run: echo AZUREAPPSERVICE_PUBLISHPROFILE and/or AZUREAPPSERVICE_APPNAME not set
    
  deploy:
    # only runs if publish profile and app name are set in GitHub
    if: ${{ needs.should-deploy.outputs.foo == 'true' }}
    runs-on: ubuntu-latest
    needs: [build, should-deploy]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZUREAPPSERVICE_APPNAME }} # after forking, set a repository secret for this
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }} # after forking, set a repository secret for this
          package: '*.jar'
