# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# runs whenever we push or make a PR to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest # run on an Ubuntu Virtual Machine (VM)
      
    steps:
    - uses: actions/checkout@v3 # start by downloading from GitHub to the VM

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # I have no idea what this means either

    - name: install Angular app dependencies
      run: |
        cd ./angular-app
        npm install -g @angular/cli
        npm install                 # installs non-global dependencies
        cd ..

    - name: Make Gradle Wrapper Executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Test with Gradle
      run: gradle test # does not execute integration tests